### ISSUE TITLE
Docker-Compose Metric Deployment - SUCI HTTP 404 error on v2.7.2

### ISSUE THREAD

**Issue by UsunSzkorbut** [Borjis131/docker-open5gs#10]
Hi,

when implementing 5Gs by docker compose from metrics dir, by default there is a problem:
08/06 11:15:35.284: [sbi] INFO: [27f92f30-53e5-41ef-b6b2-df3d68f76aa0] NF Instance setup [type:UDR validity:0s] (../lib/sbi/path.c:297)
08/06 11:15:35.289: [udm] WARNING: [suci-0-001-01-0000-0-0-1234567892] HTTP response error [404] (../src/udm/nudr-handler.c:86)
08/06 11:15:36.310: [sbi] INFO: [27f92f30-53e5-41ef-b6b2-df3d68f76aa0] NF Instance setup [type:UDR validity:0s] (../lib/sbi/path.c:297)
08/06 11:15:36.534: [sbi] INFO: [27f92f30-53e5-41ef-b6b2-df3d68f76aa0] NF Instance setup [type:UDR validity:0s] (../lib/sbi/path.c:297)
08/06 11:15:36.535: [udm] WARNING: [suci-0-001-01-0000-0-0-1234567893] HTTP response error [404] (../src/udm/nudr-handler.c:86)
08/06 11:15:36.552: [sbi] INFO: [27f92f30-53e5-41ef-b6b2-df3d68f76aa0] NF Instance setup [type:UDR validity:0s] (../lib/sbi/path.c:297)

Problem does not accure when implementing by basic dir.

**Comment by Borjis131** [comment]
Is there a UE registered with `001011234567891` too? Does it show any kind of problem?
From the capture I see that the problems are present with `001011234567892` and `001011234567893`.
Did you add them to the database?

**Comment by UsunSzkorbut** [comment]
Hi,

I solved the issue. I had problems with mangodb. Few restarts of docker-compose with docker system prune helped.
Thx for replay @Borjis131 

Closing issue
