### ISSUE TITLE
Questions about network slicing user plane (UP) data

### ISSUE THREAD

**Issue by JP4CK3T** [Borjis131/docker-open5gs#12]
Hi, @Borjis131 

I've been running some experiments with this open source.

In this regard, I was wondering if UP data passes through UPF in a network slicing setup.

For example, UP data from `ue2` will be passed through `upf2` to the DN.

I have experimented as shown below, but it looks like the UP data is not passing through.

- Ping test on `ue2`: ping 8.8.8.8
<img width="391" alt="image" src="https://github.com/user-attachments/assets/92ccd31e-5b1b-4d51-a9a5-f7c286f3fcbe">

Dump packets from `upf2`: tcpdump -i any -nn
<img width="519" alt="image" src="https://github.com/user-attachments/assets/bfc85eb2-0f2b-4dc6-8398-d9f219c8a9d3">

Can you shed some light on the UE data flow?

**Comment by JP4CK3T** [comment]
Additionally, I'm sharing the wireshark screen from the `ue2` ping test.

ICMP messages from ue2 seem to be arriving at 8.8.8.8 directly. where 10.33.33.16 is the container IP of `ue2`?
<img width="787" alt="image" src="https://github.com/user-attachments/assets/7736f4df-de98-45fb-aa41-be516b31148c">


Also, the GTP protocol is not being captured while processing the UP data.
<img width="788" alt="image" src="https://github.com/user-attachments/assets/673b9c85-cf51-4250-8fa9-1d5e2443227b">

**Comment by JP4CK3T** [comment]
I forgot some important settings while experimenting.

I registered the information for `ue1` and `ue2` via the WEBUI, ran the experiment again, and it worked correctly.

- Ping test on ue1: ping -I uesimtun0 8.8.8.8
<img width="470" alt="image" src="https://github.com/user-attachments/assets/0d009d5c-7142-4021-a324-f71270918074">

<img width="786" alt="image" src="https://github.com/user-attachments/assets/59b54e13-d59a-4fc4-900f-75f410b446b5">

- Dump packets from upf1: tcpdump -i ogstun -nn

<img width="549" alt="image" src="https://github.com/user-attachments/assets/b1507925-841e-496f-bfa7-8fc2190c4509">

<img width="787" alt="image" src="https://github.com/user-attachments/assets/ada3e9f6-3701-4bd6-9d8b-8de9015b68ca">

I think we can delete this issue.

**Comment by Borjis131** [comment]
That is what I was goint to say! You forgot to specify the UE's interface. Keep in mind that is the interface simulating the UE's connection.

Closing the issue, thank you for using the project! 😄
