### ISSUE TITLE
webui

### ISSUE THREAD

**Issue by icea-conf** [Borjis131/docker-open5gs#2]
Hi, @Borjis131 .
It was confirmed that the core was operating normally. 
I know open5gs provides webui, how can I use webui as a container?

**Comment by Borjis131** [comment]
Hi @icea-conf, 
right now I do not provide a separate container for the webui component, I basically use the `open5gs-dbctl` utility that comes with Open5GS to add new users into the database.

But it should be possible to add the `base-open5gs` (the container used to compile everything) to a docker compose deployment and make use of the webui through that container.

Hope it helps!

**Comment by icea-conf** [comment]
Thank you for your answer.

**Comment by v1ctory3** [comment]
Hi, @Borjis131 

By any chance, can I know how to use `open5gs-dbctl`?

**Comment by Borjis131** [comment]
Hi @v1ctory3,
It is a script located on the official Open5GS repository under [misc/db/](https://github.com/open5gs/open5gs/tree/main/misc/db). 

You will need the mongosh utility for it to work (it comes with the mongodb packages in Ubuntu). 
After that you can see all the options with:
```bash
./open5gs-dbctl
```

The basic usage is to add a user specifying  the imsi, key and opc values:
```bash
./open5gs-dbctl add {imsi key opc}
```

After that you can check the contents of the database (in the case of docker-open5gs, the database volume) with:
```bash
./open5gs-dbctl showpretty
```

Tip: If you install the mongodb packages in Ubuntu, remember to stop and disable the mongodb service or it will use the same port as the database in docker-open5gs and it will give you some problems!

**Comment by v1ctory3** [comment]
Thank you for your kind reply!
It was very helpful.

**Comment by Borjis131** [comment]
Hi @icea-conf I added the webui as a separate docker image. You can try it selecting the compose-file under `metrics/`.

**Comment by saleque143** [comment]
Hi @Borjis131 , I tried WebUI by selecting compose-file under metrics/. WebUI launching on localhost:9999

But I can not login. There is no login details described on the logs.

**Comment by saleque143** [comment]
Hi this is resolved. found in metric.md file.
