### ISSUE TITLE
About ogstun

### ISSUE THREAD

**Issue by v1ctory3** [Borjis131/docker-open5gs#3]
Hi, @Borjis131 

I'm currently trying to connect with OAI and Open5GS.

I know that in open5gs going back to daemon, you make gtp tunnels through ogstun, but I'm wondering how you can make gtp tunnels in docker-open5gs.

**Comment by Borjis131** [comment]
Hi @v1ctory3,

The ogstun TUN interfaces are handled by the UPF container automatically, it just needs the `upf.yaml` config file with the subnets defined as in Open5GS.

You can find the scripts that parse the UPF YAML config file inside the [images/upf/helper_functions.sh](https://github.com/Borjis131/docker-open5gs/blob/main/images/upf/helper_functions.sh).There is a little explanation [here](https://github.com/Borjis131/docker-open5gs/blob/main/docs/configuration.md#upf-configuration), but it just basically parses the YAML `subnet` fields in the UPF config file and opens the ogstun devices.

Test it with the `basic` deployment and then experiment a bit with the configuration file. It supports putting names on the TUN devices too!

**Comment by v1ctory3** [comment]
Thank you very much for your reply!
