### ISSUE TITLE
Unable to run open5gs-base.

### ISSUE THREAD

**Issue by r00tb33** [Borjis131/docker-open5gs#5]
Hi @Borjis131,

I've cloned the repo, build the docker images but, when I try to boot them up I am stuck at the following error...

```
$ docker-compose -f compose-files/basic/docker-compose.yaml --env-file=.env up
WARNING: The MONGODB_VERSION variable is not set. Defaulting to a blank string.
WARNING: The OPEN5GS_VERSION variable is not set. Defaulting to a blank string.
WARNING: The UBUNTU_VERSION variable is not set. Defaulting to a blank string.
WARNING: The DOCKER_HOST_IP variable is not set. Defaulting to a blank string.
WARNING: Some services (amf, ausf, bsf, nrf, nssf, pcf, smf, udm, udr, upf) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use `docker stack deploy` to deploy to a swarm.
ERROR: invalid reference format
```

Any suggestions as to what am I doing wrong?

Thanks!!

**Comment by Borjis131** [comment]
Hi @r00tb33,

Assuming you are executing everything from the root folder of the repository where the `.env` is placed, that command seems ok to me.

The `configs` key warning though, could be related to your docker compose version. Can you tell me your docker compose version? that way I can try to upgrade mine and check the warnings/errors.

Thanks a lot!

**Comment by r00tb33** [comment]
Fixed it by utilizing full path to .env

`docker-compose -f compose-files/basic/docker-compose.yaml --env-file=/home/usr/docker-open5gs/.env up `

Thanks!!
